### ISSUE TITLE
请问可以加一个时间段的过滤选项吗？

### ISSUE THREAD

**Issue by simp-lee** [czyathainan/log-analysis#2]
如题

非常感谢您的日志分析系统，简洁高效！

**Comment by czyathainan** [comment]
建议将时间作为搜索关键词，示例如下：
1.精确到某一天：17/Apr/2024:
2.精确到某一小时：17/Apr/2024:02:
3.精确到某一分钟：17/Apr/2024:02:51:
4.精确到某个连续的分钟段：17/Apr/2024:02:5
不同日志日期格式写法不一样，自己做调整即可。

**Comment by czyathainan** [comment]
建议将时间作为搜索关键词，示例如下：
1.精确到某一天：17/Apr/2024:
2.精确到某一小时：17/Apr/2024:02:
3.精确到某一分钟：17/Apr/2024:02:51:
4.精确到某个连续的分钟段：17/Apr/2024:02:5
不同日志日期格式写法不一样，自己做调整即可。

**Comment by simp-lee** [comment]
再次感谢你提供这么好用的库
